### ISSUE TITLE
Crash showing in unknown framework instead of Android or iOS

### ISSUE THREAD

**Issue by anis-mansuri** [rollbar/rollbar-flutter#122] opened 2024-01-02 12:57 UTC
We have integrated the rollbar into our flutter project.
when the rollbar logs the crash, it shows in an unknown framework. It should come under the Android or iOS framework.
Attaching screenshot.
<img width="1258" alt="Screenshot 2024-01-02 at 6 20 21 PM" src="https://github.com/rollbar/rollbar-flutter/assets/58723574/b034be95-93cd-42ea-9303-e3c4520b2566">

**Comment by zdavis-rollbar** [comment] 2024-01-10 21:05
Thanks for posting this.  We have created a ticket for our backlog and will work on it soon.

**Comment by zdavis-rollbar** [comment] 2024-01-29 18:59
Not yet.  Still on our backlog for the time being.

**Comment by zdavis-rollbar** [comment] 2024-01-29 21:28
After some research, this is actually not associated with the Flutter SDK.  I am going to close this issue and we will track it through our regular support line.

**Closed by zdavis-rollbar** 2024-01-29 21:28 UTC

**Comment by anis-mansuri** [comment] 2024-01-30 06:00
Can you please tell me what's the exact issue?
Maybe we might have made a mistake in integration, Please provide any
flutter demo to integrate.
Is there any way we can be notified in case it is fixed?

**Comment by zdavis-rollbar** [comment] 2024-01-30 14:27
The issue is with the menus in the Rollbar application and not with the SDK.   We have a backlog and will prioritize it in the near future.

**Comment by rituapplocum** [comment] 2024-06-12 05:02
Hi Zack,

Any update on the above?

**Comment by zdavis-rollbar** [comment] 2024-06-12 18:58
Hey @rituapplocum.  Its still in the backlog but moving up in priority.

**Comment by rituapplocum** [comment] 2024-09-06 10:17
Hey @zdavis-rollbar Any update on this?

**Comment by zdavis-rollbar** [comment] 2024-09-06 15:54
No update but still on the backlog.
